"""Review the tag vocabulary generated by src/build_vocab.py by LLM.
Input: thesaurus_draft.csv (from build_vocab.py)
Output: thesaurus_reviewed.csv
"""

import pandas as pd
import ollama
from src.config import VOCAB_DIR, LLM_MODEL, SEED
import json
from tqdm import tqdm

# PRACTICE Tool Use
df = pd.read_csv(VOCAB_DIR / "thesaurus_draft.csv")

# Tools
def get_broader_concept(tag: str) -> str:
    """Look up the broader (parent) concept of a tag in the thesaurus.

    Args:
        tag: The tag to look up, e.g. 'animals'.
    """
    concept = df[df["tag"] == tag].broader.to_string(index=False).strip()
    return "The broader concept of " + tag + " is: " + concept

def get_broader_concept_list() -> list[str]:
    """Return the list of broader concepts from the reviewed thesaurus."""
    return df["broader"].dropna().unique().tolist()
    

# LLM calls
def get_concept_from_llm():
    """Ask the LLM to get the broader concept of a tag using the tool."""

    tools = {"get_broader_concept": get_broader_concept}
    messages = [{'role': 'user', 'content': 'What is the broader concept of animals?'}]

    response = ollama.chat(model=LLM_MODEL, messages=messages, tools=list(tools.values()))
    messages.append(response.message)

    for call in response.message.tool_calls or []:
        fn = tools[call.function.name]
        result = fn(**call.function.arguments)
        messages.append({'role': 'tool', 'tool_name': call.function.name, 'content': str(result)})

    final = ollama.chat(model=LLM_MODEL, messages=messages)
    print(final.message.content)

    return final.message.content

def get_broader_concept_count_from_llm():
    """Ask the LLM to get the count of broader concepts using the tool."""

    tools = {
        "get_broader_concept": get_broader_concept,
        "get_broader_concept_list": get_broader_concept_list,
    }

    messages = [{'role': 'user', 'content': 'How many broader concepts do we have in total?'}]
    response = ollama.chat(model=LLM_MODEL, messages=messages, tools=list(tools.values()), options={"temperature": 0, "seed": SEED})
    messages.append(response.message)

    for call in response.message.tool_calls or []:
        fn = tools[call.function.name]
        result = fn(**call.function.arguments)
        messages.append({'role': 'tool', 'tool_name': call.function.name, 'content': str(result)})

    final = ollama.chat(model=LLM_MODEL, messages=messages, options={"temperature": 0, "seed": SEED})
    print(final.message.content)

    return final.message.content


def review_one_tag_from_llm(tag: str):
    """Ask the LLM to review a single tag and its broader concept."""

    tools = {
        "get_broader_concept": get_broader_concept,
        "get_broader_concept_list": get_broader_concept_list,
    }

    messages = [{'role': 'user', 'content': f'Get the broader concept of the tag "{tag}". then get the list of all broader concepts and check if the broader concept of "{tag}" is the the best fit. If not, suggest a better broader concept from the list. To decide between your suggestion and current category compare the reasoning why this tag belongs to each. choose the one which has a stronger relationship (e.g. Is-a is a stronger relationship than Depends-on)Also write the reasoning behind your suggestion.'}]
    response = ollama.chat(model=LLM_MODEL, messages=messages, tools=list(tools.values()), options={"temperature": 0, "seed": SEED})
    messages.append(response.message)

    for call in response.message.tool_calls or []:
        fn = tools[call.function.name]
        result = fn(**call.function.arguments)
        messages.append({'role': 'tool', 'tool_name': call.function.name, 'content': str(result)})
    
    final = ollama.chat(model=LLM_MODEL, messages=messages, options={"temperature": 0, "seed": SEED})
    print(final.message.content)
    return final.message.content



# Main review function

BATCH_SIZE = 5

SYSTEM_PROMPT = """You are a thesaurus editor. You check whether each tag is filed under the right broader concept.

Rules:
1. Choose ONLY from the allowed broader concepts.
2. Keep the current broader concept unless another one is clearly better.
3. A better concept must have a stronger relationship to the tag. Strength order: "is a" (type of) > "part of" > "used for / related to" > "depends on".
4. Reasoning: one or two short sentences. Name the relationship for the current concept and for your choice, and say which is stronger.
5. If you keep the current concept, suggested_broader_concept must be exactly the current one."""


def build_schema(concepts):
    return {
        "type": "object",
        "properties": {
            "reviews": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "tag": {"type": "string"},
                        "reasoning": {"type": "string"},  # reasoning before the answer helps small models
                        "suggested_broader_concept": {"type": "string", "enum": concepts},
                    },
                    "required": ["tag", "reasoning", "suggested_broader_concept"],
                },
            }
        },
        "required": ["reviews"],
    }


def review_batch(batch: pd.DataFrame, concepts: list[str]) -> dict:
    """Ask the LLM to review a batch of tags and their broader concepts."""

    allowed = "\n".join(f"- {c}" for c in concepts)
    items = "\n".join(
        f'{i}. tag: "{r.tag}" | current broader concept: "{r.broader}"'
        for i, r in enumerate(batch.itertuples(), 1)
    )
    user_prompt = f"Allowed broader concepts:\n{allowed}\n\nReview these tags:\n{items}\n\nReturn one review per tag."

    response = ollama.chat(
        model=LLM_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        format=build_schema(concepts),
        options={"temperature": 0, "seed": SEED},
    )
    reviews = json.loads(response.message.content)["reviews"]
    return {r["tag"]: r for r in reviews}


def review_concepts():
    """Ask the LLM to review every tag's broader concept and save the suggestions."""
    
    df = pd.read_csv(VOCAB_DIR / "thesaurus_draft.csv")
    concepts = df["broader"].dropna().unique().tolist()

    df["suggested_broader_concept"] = df["broader"]  # default: keep current
    df["reasoning"] = ""

    for start in tqdm(range(0, len(df), BATCH_SIZE)):
        batch = df.iloc[start:start + BATCH_SIZE]
        try:
            results = review_batch(batch, concepts)
        except Exception as e:
            print(f"Batch starting at row {start} failed: {e}")
            continue

        for idx, row in batch.iterrows():
            r = results.get(row["tag"])
            if r:
                df.at[idx, "suggested_broader_concept"] = r["suggested_broader_concept"]
                df.at[idx, "reasoning"] = r["reasoning"]

    same = df["broader"] == df["suggested_broader_concept"]
    df.loc[same, "reasoning"] = ""
    df.to_csv(VOCAB_DIR / "thesaurus_reviewed.csv", index=False)
    return df

   


if __name__ == "__main__":
    review_concepts()
    